version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: rp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rp-lending
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: rp_adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: