micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  application:
    name: rp-lending-api
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/rp-lending
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
    entity-scan:
      packages:
        - com.rp.repository.domain